language: php

php:
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5
  - 5.6

before_script:
  - sudo apt-get update > /dev/null
  - sudo apt-get install -y --force-yes apache2 libapache2-mod-php5 php5-curl php5-mysql php5-intl
  - sudo sed -i -e "/DocumentRoot/i\ServerName testing.dev" /etc/apache2/sites-available/default
  - echo "127.0.0.1 testing.dev" | sudo tee -a /etc/hosts
  - sudo /etc/init.d/apache2 restart
  - npm install -g bower
  - bower install
  - composer install -n
  - "sh -e /etc/init.d/xvfb start"
  - "export DISPLAY=:99.0"
  - "wget http://selenium.googlecode.com/files/selenium-server-standalone-2.31.0.jar"
  - "java -jar selenium-server-standalone-2.31.0.jar > /dev/null &"
  - sleep 5

script:
  - php bin/phpspec run
  - php bin/behat --stop-on-failure
